### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio' 

### ISSUE THREAD

**Issue by Beach77** [basujindal/stable-diffusion#118]
When I run Launch WebUI for stable diffusion I get this error: 

`/content/stable-diffusion
Traceback (most recent call last):
  File "/content/stable-diffusion/scripts/webui.py", line 3, in <module>
    from frontend.frontend import draw_gradio_ui
  File "/content/stable-diffusion/frontend/frontend.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'`

**Comment by Beach77** [comment]
Sorry posted to the wrong place
