### ISSUE TITLE
FirstStage object has no attribute 'get_first_stage_encoding'

### ISSUE THREAD

**Issue by SceneryCoaster** [basujindal/stable-diffusion#16]
Traceback (most recent call last):
  File "optimizedSD/optimized_img2img.py", line 259, in <module>
    init_latent = modelFS.get_first_stage_encoding(modelFS.encode_first_stage(init_image))  # move to latent space
  File "C:\Users\<me>\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'FirstStage' object has no attribute 'get_first_stage_encoding'

passed both a jpg and png image to see if it had anything to do with filetype and it does not work for either

**Comment by oxysoft** [comment]
The optimizedSD scripts don't instantiate the root model which is a `ldm.models.diffusion.ddpm.LatentDiffusion` object, which has `get_first_stage_encoding`.

**Comment by IK3Holy** [comment]
I am also getting this error, there any way to fix it?

**Comment by shade1er** [comment]
same here. did not find how to fix it atm

**Comment by oxysoft** [comment]
I found it, in `optimizedSD/` there is a ddpm.py file, you must replace the one in stable diffusion with this one.

**Comment by pandoras-rabbithole** [comment]
> 

thanks.  weird, it worked once, and the next time i started it up it won't work anymore.  same error.  double-checked the file to make sure it didn't magically revert.  no idea why this is happening
