### ISSUE TITLE
Trouble when trying to run the example command. 

### ISSUE THREAD

**Issue by RagnarTitanbane** [basujindal/stable-diffusion#21]
I ran this through conda powershell prompt
(ldm) PS D:\stable-diffusion> python optimizedSD/optimized_img2img.py --prompt "Austrian alps" --init-img ~/sketch-mountains-input.jpg --strength 0.8 --n_iter 2 --n_samples 5 --H 576 --W 768
Traceback (most recent call last):
  File "optimizedSD/optimized_img2img.py", line 16, in <module>
    from ldm.util import instantiate_from_config
  File "C:\Users\ebarr\miniconda3\envs\ldm\lib\site-packages\ldm.py", line 77
    print os.path.exists("%s.bz2"%(predictor_path))
          ^
SyntaxError: invalid syntax

**Comment by RagnarTitanbane** [comment]
Oh that was with img2img example, it also does that with txt2img too

**Comment by RagnarTitanbane** [comment]
I'm pretty sure I fixed it, I just installed things wrong or something, sorry for the trouble
