### ISSUE TITLE
No module found named 'optimizedSD'

### ISSUE THREAD

**Issue by kmcnayr** [basujindal/stable-diffusion#219]
I did not use Docker and just installed everything in a virtualenv. getting no module error. anyone have any ideas?

Global seed set to 27
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
Traceback (most recent call last):
  File "optimizedSD/optimized_txt2img.py", line 210, in <module>
    model = instantiate_from_config(config.modelUNet)
  File "~/optimSD/optimizedSD/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "~/optimSD/optimizedSD/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'optimizedSD'

**Comment by darraghoriordan** [comment]
you have to `pip install -e .` in the "root" of stable-diffusion

**Comment by jerrykurtin** [comment]
> you have to `pip install -e .` in the "root" of stable-diffusion

Thank you! What does this do, exactly?

**Comment by ForgetAll** [comment]
> you have to `pip install -e .` in the "root" of stable-diffusion

works for me, thanks
