### ISSUE TITLE
ImportError: cannot import name 'Doc' from 'typing_extensions'

### ISSUE THREAD

**Issue by gmammolo** [basujindal/stable-diffusion#245]
During the first boot, after the Docker command `docker compose up --build`, I get this error:

> optimizedstablediffusion-sd-1  | Clearing symlinks in /etc/ssl/certs...
optimizedstablediffusion-sd-1  | done.
optimizedstablediffusion-sd-1  | Updating certificates in /etc/ssl/certs...
optimizedstablediffusion-sd-1  | rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
optimizedstablediffusion-sd-1  | 137 added, 0 removed; done.
optimizedstablediffusion-sd-1  | Running hooks in /etc/ca-certificates/update.d...
optimizedstablediffusion-sd-1  | done.
optimizedstablediffusion-sd-1  | Traceback (most recent call last):
optimizedstablediffusion-sd-1  |   File "optimizedSD/txt2img_gradio.py", line 1, in <module>
optimizedstablediffusion-sd-1  |     import gradio as gr
optimizedstablediffusion-sd-1  |   File "/venv/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
optimizedstablediffusion-sd-1  |     import gradio.components as components
optimizedstablediffusion-sd-1  |   File "/venv/lib/python3.8/site-packages/gradio/components.py", line 39, in <module>
optimizedstablediffusion-sd-1  |     from gradio.blocks import Block
optimizedstablediffusion-sd-1  |   File "/venv/lib/python3.8/site-packages/gradio/blocks.py", line 19, in <module>
optimizedstablediffusion-sd-1  |     from gradio import (
optimizedstablediffusion-sd-1  |   File "/venv/lib/python3.8/site-packages/gradio/event_queue.py", line 8, in <module>
optimizedstablediffusion-sd-1  |     import fastapi
optimizedstablediffusion-sd-1  |   File "/venv/lib/python3.8/site-packages/fastapi/__init__.py", line 7, in <module>
optimizedstablediffusion-sd-1  |     from .applications import FastAPI as FastAPI
optimizedstablediffusion-sd-1  |   File "/venv/lib/python3.8/site-packages/fastapi/applications.py", line 16, in <module>
optimizedstablediffusion-sd-1  |     from fastapi import routing
optimizedstablediffusion-sd-1  |   File "/venv/lib/python3.8/site-packages/fastapi/routing.py", line 22, in <module>
optimizedstablediffusion-sd-1  |     from fastapi import params
optimizedstablediffusion-sd-1  |   File "/venv/lib/python3.8/site-packages/fastapi/params.py", line 5, in <module>
optimizedstablediffusion-sd-1  |     from fastapi.openapi.models import Example
optimizedstablediffusion-sd-1  |   File "/venv/lib/python3.8/site-packages/fastapi/openapi/models.py", line 4, in <module>
optimizedstablediffusion-sd-1  |     from fastapi._compat import (
optimizedstablediffusion-sd-1  |   File "/venv/lib/python3.8/site-packages/fastapi/_compat.py", line 20, in <module>
optimizedstablediffusion-sd-1  |     from fastapi.exceptions import RequestErrorModel
optimizedstablediffusion-sd-1  |   File "/venv/lib/python3.8/site-packages/fastapi/exceptions.py", line 6, in <module>
optimizedstablediffusion-sd-1  |     from typing_extensions import Annotated, Doc  # type: ignore [attr-defined]
optimizedstablediffusion-sd-1  | ImportError: cannot import name 'Doc' from 'typing_extensions' (/venv/lib/python3.8/site-packages/typing_extensions.py)

**Comment by justADeni** [comment]
Same here! Tried changing typing_extensions version in Docker file with pip commands but that didn't work
