### ISSUE TITLE
No module named 'optimizedSD'

### ISSUE THREAD

**Issue by drallcom3** [basujindal/stable-diffusion#35]
When trying to run
`python optimizedSD/optimized_img2img.py`
I get the error below. The non-optimized img2img works fine.

It's something with `optimizedSD.ddpm.UNet` in `v1-inference.yaml`.

Traceback (most recent call last):
  File "optimizedSD/optimized_img2img.py", line 224, in <module>
    model = instantiate_from_config(config.modelUNet)
  File "c:\git\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "c:\git\stable-diffusion\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "C:\Users\Christoph\miniconda3\envs\ldm\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'optimizedSD'

**Comment by aravind598** [comment]
It works fine on my end. I moved the optimisedSD folder to the original repo folder and ran your above line no error. Also my current directory was the original stable diffusion repo. Hope this helps

**Comment by iori-komatsu** [comment]
I also encountered the same issue. In my case, the following steps solved the problem:

```bash
# Run in the top directory of this repository.
conda env remove -n ldm
conda env create -f environment.yaml
conda activate ldm
```

**Comment by neonsecret** [comment]
this happens because you dont install this repo as library, you can solve it without reinstalling the env by running:
`pip install -e .`
