### ISSUE TITLE
txt2img_gradio.py error

### ISSUE THREAD

**Issue by lessirey** [basujindal/stable-diffusion#83]
I am now getting this error while loading txt2img_gradio.py

Traceback (most recent call last):
  File ".\optimizedSD\txt2img_gradio.py", line 225, in <module>
    demo = gr.Interface(
AttributeError: module 'gradio' has no attribute 'Interface'

**Comment by basujindal** [comment]
Hi, can you try updating to the latest version of gradio?

**Comment by lessirey** [comment]
tried it, still getting error, on a different line though:

Traceback (most recent call last):
  File ".\optimizedSD\txt2img_gradio.py", line 228, in <module>
    demo = gr.Interface(
AttributeError: module 'gradio' has no attribute 'Interface'

**Comment by Orthestral** [comment]
Did you only update this repo? He meant updating the Gradio package itself. `pip install -U gradio`
