### ISSUE TITLE
TypeError: sample() got an unexpected keyword argument 'sampler'

### ISSUE THREAD

**Issue by slack-t** [basujindal/stable-diffusion#92]
Pulled the latest from a couple of minutes ago...

Unfortunately I can't run it:

`Global seed set to 717834
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
FirstStage: Running in eps-prediction mode
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
data:   0%|                                                                                      | 0/1 [00:01<?, ?it/s]
Sampling:   0%|                                                                                  | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "optimizedSD\optimized_txt2img.py", line 290, in <module>
    samples_ddim = model.sample(
  File "C:\Users\linux\.conda\envs\ldo\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: sample() got an unexpected keyword argument 'sampler'
`

**Comment by basujindal** [comment]
Hi, can you once try replacing the latest ddpm.py file from this repo?

**Comment by slack-t** [comment]
Hi,

I did, but still exact the same error...

Much respect for your great work!!!

**Comment by florian-kalisch** [comment]
Hi,
I got the error too, but updating ddpm.py fixed it.
I guess I was too excited to test the functionality :D and didn't pay attention to all the changes.

By the way, big thanks for your great work and continuous improvement. Just awesome.

**Comment by chielteuben** [comment]
@slack-t try to run a conda env update and see if this resolves the issue, it did for me.

**Comment by slack-t** [comment]
Hi all!
@chielteuben Thank you for the suggestion. I think it worked. I did a git pull to the latest commit and ran conda env update -f environment.yaml
At least I'm not getting the TypeError anymore. PLMS works again as before. 
However I cannot use the DDIM sampler (that's what this commit was about, right? Although the commit message says adding PLMS sampler?) as it throws the following

`python optimizedSD\optimized_txt2img.py --prompt "android woman with pink hair, photojournalism, realistic" --n_iter 1 --H 512 --W 512 --sampler ddim
Global seed set to 377902
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
FirstStage: Running in eps-prediction mode
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Sampling:   0%|                                                                                  | 0/1 [00:00<?, ?it/s]x0 None  0%|                                                                                      | 0/1 [00:00<?, ?it/s]
seeds used =  [377902, 377903, 377904, 377905, 377906]
data:   0%|                                                                                      | 0/1 [00:02<?, ?it/s]
Sampling:   0%|                                                                                  | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "optimizedSD\optimized_txt2img.py", line 290, in <module>
    samples_ddim = model.sample(
  File "C:\Users\linux\.conda\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\users\linux\forks\stable-diffusion\optimizedSD\ddpm.py", line 529, in sample
    samples = self.ddim_sampling(x_latent, conditioning, S, unconditional_guidance_scale=unconditional_guidance_scale,
  File "C:\Users\linux\.conda\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\users\linux\forks\stable-diffusion\optimizedSD\ddpm.py", line 687, in ddim_sampling
    timesteps = self.ddim_timesteps
  File "C:\Users\linux\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet' object has no attribute 'ddim_timesteps'`

**Comment by slack-t** [comment]
Closing this as a new issue has been raised for the AttributeError: 'UNet' object has no attribute 'ddim_timesteps' error. See #98 

Fix for this issue was updating the conda env. Thank you @chielteuben and @basujindal

**Comment by aadnk** [comment]
> Closing this as a new issue has been raised for the AttributeError: 'UNet' object has no attribute 'ddim_timesteps' error. See #98
> 
> Fix for this issue was updating the conda env. Thank you @chielteuben and @basujindal

I tried using the latest commit (d42597ec4dc922114e1bdec0df28320f5b058d11) and updating my Conda environment (conda env update -f environment.yaml), but I'm still getting the sampler issue on Windows:
```
  File "optimizedSD/optimized_txt2img.py", line 296, in <module>
    samples_ddim = model.sample(
  File "C:\Dev\Anaconda\envs\ldo\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: sample() got an unexpected keyword argument 'sampler'
```
I get a similar error when running the gradio interface:
```
Traceback (most recent call last):
  File "C:\Dev\Anaconda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Dev\Anaconda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Dev\Anaconda\envs\ldo\lib\site-packages\gradio\blocks.py", line 554, in call_function
    prediction = await block_fn.fn(*processed_input)
  File "C:\Dev\Anaconda\envs\ldo\lib\site-packages\gradio\interface.py", line 651, in submit_func
    prediction = await self.run_prediction(args)
  File "C:\Dev\Anaconda\envs\ldo\lib\site-packages\gradio\interface.py", line 680, in run_prediction
    prediction = await anyio.to_thread.run_sync(
  File "C:\Dev\Anaconda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Dev\Anaconda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Dev\Anaconda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "optimizedSD\inpaint_gradio.py", line 242, in generate
    samples_ddim = model.sample(
  File "C:\Dev\Anaconda\envs\ldo\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: sample() got an unexpected keyword argument 'sampler'
```
But commit 5c0248aa7d4d3cd464ef5da7e6b74686775a9cf8 still works though.

My environment is as follows:
[conda_environment.txt](https://github.com/basujindal/stable-diffusion/files/9468843/conda_environment.txt)
