### ISSUE TITLE
Assertion error when using img2img with gradio

### ISSUE THREAD

**Issue by LuciferSam86** [basujindal/stable-diffusion#95]
Update: https://github.com/hlky/stable-diffusion-webui/issues/405 since the webui.py was taken from that project

Here the trace
Traceback (most recent call last):
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1288, in img2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 691, in process_images
    assert prompt is not None
AssertionError

another thing : it should have updated something that broke even the mask : the cursor is moving like it's having some weird offset

hmm : I followed a guide to overwrite the web-ui from this another project https://github.com/hlky/stable-diffusion-webui . 
But until yesterday it worked everything like a charm. Any suggestions?

**Comment by LuciferSam86** [comment]
Welp I'm an idiot : i did not write the prompt. Closing the issue :/
