### ISSUE TITLE
cannot import name VectorQuantizer2

### ISSUE THREAD

**Issue by samuel-reyes** [basujindal/stable-diffusion#96]
I did a fresh clone of the official SD repo today and setup a fresh conda environment. When I added the optimizedSD folder and I try to run it I get the following. Any ideas how to resolve this?

samuel@system% python optimizedSD/txt2img_gradio.py

                          
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
Traceback (most recent call last):
  File "optimizedSD/txt2img_gradio.py", line 66, in <module>
    model = instantiate_from_config(config.modelUNet)
  File "/mnt/e/StableDiffusion/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/mnt/e/StableDiffusion/stable-diffusion/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/home/samuel/anaconda3/envs/ldm/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/e/StableDiffusion/stable-diffusion/optimizedSD/ddpm.py", line 15, in <module>
    from ldm.models.autoencoder import VQModelInterface
  File "/mnt/e/StableDiffusion/stable-diffusion/ldm/models/autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ImportError: cannot import name 'VectorQuantizer2' from 'taming.modules.vqvae.quantize' (/home/samuel/anaconda3/envs/ldm/lib/python3.8/site-packages/taming/modules/vqvae/quantize.py)

**Comment by basujindal** [comment]
Hi, can you once try upading the conda env using `conda env update -f environment.yaml`?

**Comment by tabishz** [comment]
for me I was getting similar but different error, "ModuleNotFoundError: No module named 'optimizedSD'"

however, ```conda env update -f environment.yaml``` and ```conda update -n base -c defaults conda``` fixed it for me.
