### ISSUE TITLE
ddim sampler - AttributeError: 'UNet' object has no attribute 'ddim_timesteps'

### ISSUE THREAD

**Issue by C00reNUT** [basujindal/stable-diffusion#99]
Hello, 
thank you for this wonderful implementation.

When using ddim sampler in case of txt2img 

`python optimizedSD/optimized_txt2img.py --prompt "nice cat" --H 704 --W 512 --seed 221277 --n_iter 15 --n_samples 2 --ddim_steps 50 --turbo --sampler ddim`

I get the following error

```
Traceback (most recent call last):
  File "optimizedSD/optimized_txt2img.py", line 290, in <module>
    samples_ddim = model.sample(
  File "/mnt/2287294e-32c7-437b-84bd-452a29548b1a/conda_env/stable_diffusion/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/2287294e-32c7-437b-84bd-452a29548b1a/Graphics/stable_diffusion/stable-diffusion/optimizedSD/ddpm.py", line 529, in sample
    samples = self.ddim_sampling(x_latent, conditioning, S, unconditional_guidance_scale=unconditional_guidance_scale,
  File "/mnt/2287294e-32c7-437b-84bd-452a29548b1a/conda_env/stable_diffusion/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/2287294e-32c7-437b-84bd-452a29548b1a/Graphics/stable_diffusion/stable-diffusion/optimizedSD/ddpm.py", line 687, in ddim_sampling
    timesteps = self.ddim_timesteps
  File "/mnt/2287294e-32c7-437b-84bd-452a29548b1a/conda_env/stable_diffusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet' object has no attribute 'ddim_timesteps'
```

**Comment by C00reNUT** [comment]
Ou, I see you have fixed it with the recent commit :) Thank you!
